### PR TITLE
Dtportal 16289 update cloudvox fork from kares

### PR DESCRIPTION
**Pull request by gfaza**

### CODE REVIEW

**Comment by gfaza** [comment]
attn @sfgeorge - was unable to get travis to pass, despite a number of tweaks to .travis.yml

**Comment by sfgeorge** [comment]
@gfaza Can you remove `1.9.2` from .travis.yml?  And it looks like [rbx-19mode is no longer a thing](https://github.com/travis-ci/travis-ci/issues/1641#issuecomment-29009870).  You should be able to try `rbx` or `rbx-4` and hopefully one of those works 🤞

**Comment by sfgeorge** [comment]
@gfaza Sorry, bad intel.  Can you give `rbx-4` a shot?

**Comment by gfaza** [comment]
@sfgeorge rbx-4 doesn't work either :(

**Comment by sfgeorge** [comment]
@gfaza  I’m sorry for the back-and-forth on this one.  I just had the hunch that it must be sooo close.  Can you give rbx-3 a shot, and if that don’t work, then move rbx-4 to allowed_failures?

**Review by sfgeorge — APPROVED** [review]
@gfaza Thank you!!! 👍 

@mattcar Can you merge this for us?

**Pull request merged**
